---
note_type: note
tags:
  - web_development
  - javascript
  - typescript
  - async
mn: "[[12.14 Typescript]]"
kt: theorical
checked: false
---
[[12.14 Typescript|Typescript]]
# About promises
Promises are objects that encapsulates the return value of an async operation which can be successful or failure. To use promises in TS the `"target"` property in the `tsconfig.json` file needs to be at least `ES2015`. Instance methods of promises also return promises, hence, I can chain promises. 

# Creating a promise
Promises are created passing a callback to its constructor. This callback will define the async operation, it has two parameters.

This is a user defined function that can be passed to the promise constructor.  The `resolve` and `reject` are functions the promise object understands. 

If the result of the async is successful, invoke the `resolve` function passing any data I want to make available to the code that will process the result. If something goes wrong, use `reject`

```ts
function doAsyncWord(resolve, reject){
  if (success) resolve (data);
  else reject(reason);  
}
```

Then, add the promise as a parameter to the promise constructor. The type annotation is using the generic syntax, and what's inside of `<>` indicates the data type is going to be return if the promise is resolve successfully. 

```ts
let p: Promise<string> = new Promise(doAsyncWork);
```

Is more common to pass, instead of the user defined function, an arrow function.

![[Pasted image 20250218083652.png]]

# Handling the promise result
To handling the result use either the `then` and `catch` instance methods. 

If the promise resolve successfully, then type the promise according to the type it should return, string in this example. In this example, the method returns a promise. 

```ts
let p: Promise<string> = MethodsThaReturnsPromise();
```

Then, use the promise object `p` to register functions that should be called when the async code succeeds or fails. The is called when the promise is resolve successfully. The `stringData` parameter will receive the data passed to the `resolve` method of the promise.  

Then, returns a promise object, so I can chain the `catch` function that will handle any errors. `catch` will only be executed if the promise is rejected or thrown an exception in the `then` function. `catch`'s argument, named `reason` in this example, receives the value passed to the `reject` function in the promise function. 

```ts
p.then(stringData => console.log(stringData))
 .catch(reason => console.log(reason));
```

Detail the promise is annotate in the function signature.

![[Pasted image 20250220091803.png]]

