---
note_type: note
tags:
  - web_development
  - javascript
  - promises
mn: "[[12.5 Javascript]]"
kt: theorical
checked: false
---
[[12.5 Javascript|JavaScript]]

Promise reaction records (`[[PromiseFulfillReactions]]`, `[[PromiseRejectReactions]]`) have handlers (callback pass to `.then` and `.catch` methods) that have the code will be executed code depending on `[[PromiseState]]` value, meaning they don't immediately execute, and have to wait **once the promise settles**.

To create this reaction records, chain the `.then()` or `.catch()` methods to the binding of the promise or the promise constructor. 
## Then
In the basic syntax, the first argument executes a callback if the promise is resolve and a result is received. The second argument is a callback if the promise is rejected and an error is received. 

Each `then()` returns a promise object. 

The promise reaction record handler receives the `[[PromiseResult]]` value when it updates after the promise is resolve.

```js
promise.then(
  function(result) { /* handle a successful result */ },
  function(error) { /* handle an error */ }
);

promise.then(
  result => alert(result), 
  error => alert(error);
);

// If I have a defined functions for a successful and reject scenario
promise.then(onFulfilled, onRejected)

// This way attaches the then directly onto the constructor
new Promise ((resolve, rejeect) => {
  resolve("hi")})
  .then(result => console.log(result))
```

>[!important]
>If the promise is within a function I have to use the function identifier as an 'object name' to attach the then and catch methods.  
>```js
>function test () {
>  return new Promise((resolve, reject) => {
>    resolve("hi")}
>  )
>}
>test().then(...)
>  .then(...);
>```
### Then chaining
Each `then` receives the result of the precious `then`'s return value. Also each then returns a new promise object. Chain results **require** me to return something on all then call, 
>[!blank-container|float-left-medium]
>```js
>new Promise(function(resolve, reject) { 
>	// A mock async action using setTimeout
>	setTimeout(function() { resolve(10); }, 3000);
>})
>.then(function(num) { console.log('first then: ', num); return num * 2; })
>.then(function(num) { console.log('second then: ', num); return num * 2; })
>.then(function(num) { console.log('last then: ', num);});
>
>// first then:  10
>// second then:  20
>// last then:  40
>```


![[Pasted image 20240918093205.png|centere|150]]




This is different to add multiple then to an promise object.
>[!blank-container|float-left-medium]
>```js
>let promise = new Promise(function(resolve, reject) {
>  setTimeout(() => resolve(1), 1000);
>});
>
>promise.then(function(result) {
>  alert(result); // 1
>  return result * 2;
>});
>
>promise.then(function(result) {
>  alert(result); // 1
>  return result * 2;
>});
>```

![[Pasted image 20240918093341.png]]


In practice we rarely need multiple handlers for one promise. Chaining .is used much more often




When I have defined functions I can chain those function in whatever order I need.

```js
getWeather()
  .then(firstDefinedFunction)
  .then(secondDefinedFunction)
```
### Example
```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve("done!"), 1000);
});

// resolve runs the first function in .then
promise.then(
  result => alert(result), // shows "done!" after 1 second
  error => alert(error) // doesn't run
);
```

```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => reject(new Error("Whoops!")), 1000);
});

// reject runs the second function in .then
promise.then(
  result => alert(result), // doesn't run
  error => alert(error) // shows "Error: Whoops!" after 1 second
);
```

If weâ€™re interested only in successful completions, then we can provide only one function argument.

```js
let promise = new Promise(resolve => {
  setTimeout(() => resolve("done!"), 1000);
});

promise.then(alert); // shows "done!" after 1 second
```

![[Pasted image 20240918093437.png|center|250]]

![[Pasted image 20250220090044.png|center|400]]
## Catch
I can use `then(null, errorHandlingFunction)` if I want to focus only in errors. Or I can use `catch()`.

```js
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("Whoops!")), 1000);
});

// .catch(f) is the same as promise.then(null, f)
promise.catch(alert); // shows "Error: Whoops!" after 1 second
```

## Adding then and catch functions
Though is more clear to attached the then and catch functions using dot notation like a regular object, like in the above examples, and I can also do this (though is ugly):

```js
new Promise(function(resolve, reject) {
	// A mock async action using setTimeout
	setTimeout(function() { reject('Done!'); }, 3000);
})
.then(function(e) { console.log('done', e); })
.catch(function(e) { console.log('catch: ', e); });
```