---
note_type: note
tags:
  - programming
  - c#
  - web_development
  - .net_web_api
  - unit_testing
  - scenarios
mn:
  - "[[12 Web Dev]]}"
  - "[[13.9 ASP.NET Core Web API]]"
kt: theorical
checked:
---
[[13.9 ASP.NET Core Web API|ASP.NET Core Web API]]

This kind of test check whether the code throws assert or exceptions. Mustbethrown.

This test will test if, after given an employee the minimum raise, the api must return an exception if I try to give him the same minimum raise. 

This is the method to test.

![[Pasted image 20250228110311.png]]

![[Pasted image 20250228105854.png]]

 For testing exceptions I need to bundle the act and assert. Use throws async, with the type being the exception I except, then use a lambda with async and call the method that should generate an exception, in this case give raise async 50, should be more than 100.

This test pass.

![[Pasted image 20250228110156.png]]

Now,  detail what happen if the method change the exception.

![[Pasted image 20250228110351.png]]

It fails because is throwing another kind of exception.

![[Pasted image 20250228110411.png]]

## Mistake here
This is a mistake, when I use throws async, I must await the test, if not, the test will not work properly. 

![[Pasted image 20250228110459.png]]

# Another kind of assert exceptions
![[Pasted image 20250228110723.png]]

